### ISSUE TITLE
eratic behavior on linux using Wine

### ISSUE THREAD

**Issue by jrgensol** [gemforce-team/wGemCombiner#5] opened 2015-05-18 17:05 UTC
It seems a bit random whether or not the wGemCombiner finishes the gem correctly or not when using linux mint and Wine. In the video I tried to make a managem three times, only one was a success. I know it is not released for linux, but any idea if the problem is with the gemcombiner or with the rest of my system?
https://youtu.be/mvseIJX6M3g

**Comment by 12345ieee** [comment] 2015-05-18 17:31
I'm actually incredibly impressed it works at all.
Back in December when we released it I tested it under Wine 1.6.something in Debian testing and it crashed in horrible ways, so I gave up to make it work under Linux.

Now I am on Fedora with Wine 1.7.41 and it seems to work well, I correctly executed the spec even with a delay of 400 ms several times.

Ultimately the issue is the huge input lag generated by the game running under Wine, nothing that me nor you can control.

You may try the debug versions listed in #4, see if one performs better.

**Comment by jrgensol** [comment] 2015-05-19 05:47
Those did not work either (all of them works some of the time). When going through the video in slow motion I saw that the problem was when combining gems, could it help if you added an option to add a few ms between the commands when combining?

**Comment by 12345ieee** [comment] 2015-05-25 21:56
Sorry for the huge delay, I'm busy with other stuff.
Maybe this weekend I'll try, but I don't think it'll solve the issue.

**Comment by 12345ieee** [comment] 2015-12-29 01:57
wGC 1.1 was just released.
Closed, as it's probably fixed by the new version.

**Closed by 12345ieee** 2015-12-29 01:57 UTC
Labels: Linux support
