### ISSUE TITLE
key detection failed

### ISSUE THREAD

**Issue by depthperception** [gemforce-team/wGemCombiner#12] opened 2015-06-25 08:04 UTC
I keep getting this message almost randomly "key detection failed, or you were already holding 9. Try again." once the message comes up the first time it doesn't go away no matter what I do. even closing the program and reopening it does not fix the issue. Then randomly it starts working again.

I am playing on kongrigate.com on win7. when the program works it works great but when it doesn't....

**Comment by 12345ieee** [comment] 2015-06-25 15:21
I know, the issue is fixed on PR #9, I just need to get around, test and
release it

2015-06-25 10:04 GMT+02:00 depthperception <notifications@github.com>:

**Comment by depthperception** [comment] 2015-06-25 17:49
I'm glad to hear you know about the issue and there will be a fix for it. Do you know of a work around for the short term?

**Comment by CooLTanG** [comment] 2015-06-25 17:53
My version ignores the popup message, and has a lot more fixes and is simplified, just need to pick a spec and then just press "9" over the gem for it to work.

https://github.com/CooLTanG/wGemCombiner/releases

**Comment by 12345ieee** [comment] 2015-06-26 00:36
@CooLTanG Man, I understand you want your version to release, but I've been busy this period (exams, so many exams).
If you want to release faster, test that it works for every combination (Flash windows at normal size and Steam version at every size you support with the handle), as that is the longest thing to do and I cannot do it atm.

**Comment by CooLTanG** [comment] 2015-06-26 01:47
I have tested it, but its fine I'll continue to use it. You can release it whenever your free to.

**Comment by IsaacsLaughing** [comment] 2015-06-27 03:53
While working on this, would an option to change the hotkey be possible?

**Comment by 12345ieee** [comment] 2015-06-27 12:35
@IsaacsLaughing Submit this as a new issue please, when I have time I'll
see what I can do.

2015-06-27 5:53 GMT+02:00 IsaacsLaughing <notifications@github.com>:

**Closed** 2015-07-29 21:15 UTC
