### ISSUE TITLE
(b+o) is a difference to (o+b)

### ISSUE THREAD

**Issue by BilboCGL** [gemforce-team/wGemCombiner#27] opened 2016-01-23 23:51 UTC
For the parser it makes a difference whether (b+o) is used or (o+b)
For example ((b+o)+(b+o)) takes 2 steps but ((b+o)+(o+b)) takes 5 steps.
That is of course no important issue, but maybe a point to optimize

**Comment by RobinHood70** [comment] 2016-01-24 09:02
Hmmm...yes, I can see why that would happen. I'm not sure how easy that'll be to address, though. I'll have a look into it sometime soon.

**Comment by 12345ieee** [comment] 2016-01-24 10:55
Some insight, there is a multi-layered issue:

1) Parenthesis parse "o+b" != "b+o", which is incorrect, it should not emit
the second equation at all, not leave it to the equation parser to collapse
them

2) The hashmap that the equation parser uses to check duplicates checks the
order, too, by design (it shouldn't)


My opinion is that
"""
2=0+1
3=1+0
"""
should emit a double definition error, though it could also be ignored
silently.

3) The idiot way to fix this (swapping lhs and rhs in the equation parser
if they are in the wrong order [lhs < rhs]) introduces other issues.

Good luck with this, @RobinHood70

2016-01-24 10:02 GMT+01:00 Robert Morley <notifications@github.com>:

**Comment by RobinHood70** [comment] 2016-01-25 18:49
Okay, I've added some code to handle these types of issues. It might not work in really complex cases, I'm not sure, but I think it should work well enough for basic cases. The parenthetic parser simply does a search for both x+y and y+x, while the equation parser always sorts the highest number first and checks for duplicates as normal based on that. I think that should address all of the issues above, but if there's something I'm not seeing (whatever issues you mean in point 3), please let me know.

**Comment by 12345ieee** [comment] 2016-01-25 18:57
Reviewing....
In the meantime, be careful that you are still on your old testing
branch, that branched off from v1.1 instead of the newest state.
Please put (NOT merge) your new commit on top of master

Il 25/01/2016 19:49, Robert Morley ha scritto:

**Comment by 12345ieee** [comment] 2016-01-25 19:05
I confirm the issue I saw was solved (by the parenthesis matching code).

An extremely minor nitpick, if you give an equation with a
2=0+1
3=1+0
chain, the error is "1+0 appears multiple times".
Changing it to "1+0/0+1 ..." might help some confusion.

Great work, thanks @RobinHood70 .

**Comment by RobinHood70** [comment] 2016-01-25 19:19
Yeah, I couldn't see an easy way around that, since it's just the basic duplicate parser that's picking it up.

As for your instructions about what to do with Git, I'm not entirely sure I followed, but I think so. I'll have a look at it and try a commit shortly.

**Comment by RobinHood70** [comment] 2016-01-25 19:30
Okay, I just cut & pasted the same changes to the master branch. Not sure if that's what you were suggesting I do, but it gets the job done, anyway. (Sorry, Git might as well be written in Chinese for all the sense it makes to me.)

**Comment by 12345ieee** [comment] 2016-01-25 20:25
Yes, it did the job, the only problem is that the commit message makes
no sense at all now, but no big issue.

Il 25/01/2016 20:30, Robert Morley ha scritto:

**Comment by 12345ieee** [comment] 2016-02-18 23:17
Why is this still open?

Fixed by @RobinHood70 in commit a42820a031d936b30edfe8e3b37637d93dc0bf44.
Closing.

**Closed by 12345ieee** 2016-02-18 23:17 UTC
